# Generated by Django 6.0.3 on 2026-03-15 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('representative_type', models.CharField(choices=[('SARPANCH', 'Sarpanch'), ('CHAIRPERSON', 'Chairperson')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='representatives/')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('local_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='locations.localbody')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
