# Generated by Django 6.0.3 on 2026-03-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional. Used for OTP when Sarpanch logs in.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
