# Generated by Django 5.2.13 on 2026-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0002_representative_email_optional_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
