"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv():
    """Load KEY=VALUE lines from BASE_DIR/.env (no extra packages)."""
    env_path = BASE_DIR / ".env"
    if not env_path.is_file():
        return
    for raw in env_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip().strip("'").strip('"')
        if key and key not in os.environ:
            os.environ[key] = val


_load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--2-yspnbjp$9&fy(ify)z(&$*t)hwqon$@2*(tqfdioay+w#+8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Local dev + optional LAN (set e.g. DJANGO_ALLOWED_HOSTS=192.168.1.5 in .env)
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
_extra_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if _extra_hosts:
    ALLOWED_HOSTS.extend(h.strip() for h in _extra_hosts.split(",") if h.strip())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'accounts',
    'locations',
    'representatives',
    'payments',
    'advertisements',
    'adminpanel',
    'public',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.email_dev_hint',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Cache (OTP for Sarpanch login, rate limits)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "sarpanch-app-cache",
    }
}

# Sarpanch OTP
SARPANCH_OTP_TTL = int(os.environ.get("SARPANCH_OTP_TTL", "600"))  # seconds
SARPANCH_OTP_MAX_SENDS_PER_HOUR = int(os.environ.get("SARPANCH_OTP_MAX_SENDS_PER_HOUR", "10"))

# App user password reset (SMS + email OTP; same 6-digit code)
PASSWORD_RESET_OTP_TTL = int(os.environ.get("PASSWORD_RESET_OTP_TTL", "600"))
PASSWORD_RESET_OTP_MAX_SENDS_PER_HOUR = int(
    os.environ.get("PASSWORD_RESET_OTP_MAX_SENDS_PER_HOUR", "10")
)

# SMS: set TWILIO_* in .env for production; otherwise OTP is logged to sms_outbox/
SMS_LOG_TO_FILE = os.environ.get("SMS_LOG_TO_FILE", "1").lower() in ("1", "true", "yes")


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'railway',
        'USER': 'root',
        'PASSWORD': 'boEZDZVJrddxHDJdNBSdFYAZYRadbMAP',
        'HOST': 'nozomi.proxy.rlwy.net',
        'PORT': '12699',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------------
# Email (password reset, etc.)
# ---------------------------------------------------------------------------
# 1) REAL EMAIL: set SMTP in .env. With DEBUG=True you must also set
#    EMAIL_USE_SMTP_IN_DEV=1 or mail goes to email_outbox/ only (no SMTP).
#
# 2) DEV (DEBUG=True): each email is one file under email_outbox/
#    (name like email_YYYYMMDD-HHMMSS_<id>.txt). Open the newest to copy the link.
#
# 3) Console: only used if DEBUG=False and SMTP not configured.
#
# Note: Django sends NOTHING (no file, no console) if no *active* User has
# that exact email — see password reset message on the next page.

_smtp_creds = bool(
    os.environ.get("EMAIL_HOST_USER", "").strip()
    and os.environ.get("EMAIL_HOST_PASSWORD", "").strip()
)
_smtp_disabled = os.environ.get("USE_SMTP_EMAIL", "").strip().lower() in ("0", "false", "no")

# With DEBUG=True, prefer file outbox (password reset links) unless you opt into real SMTP.
_smtp_in_dev = os.environ.get("EMAIL_USE_SMTP_IN_DEV", "").strip().lower() in (
    "1",
    "true",
    "yes",
)
_use_smtp = (
    _smtp_creds
    and not _smtp_disabled
    and (not DEBUG or _smtp_in_dev)
)

# Real SMTP when credentials are set; in development use file outbox unless EMAIL_USE_SMTP_IN_DEV=1.
if _use_smtp:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in (
        "1",
        "true",
        "yes",
    )
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = os.environ.get(
        "DEFAULT_FROM_EMAIL",
        EMAIL_HOST_USER or "webmaster@localhost",
    )
elif DEBUG:
    # One file per email (see core.email_backends) — easier to copy password reset links.
    EMAIL_BACKEND = "core.email_backends.OneEmailPerFileBackend"
    _email_out = BASE_DIR / "email_outbox"
    _email_out.mkdir(exist_ok=True)
    EMAIL_FILE_PATH = str(_email_out)
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@localhost")
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "webmaster@localhost")

# Password reset links: validity in seconds (Django 4+). Min 120s; default 24 hours.
PASSWORD_RESET_TIMEOUT = max(
    120,
    int(os.environ.get("PASSWORD_RESET_TIMEOUT", "86400")),
)

# Optional Twilio SMS for Sarpanch OTP (see representatives/otp.py)
TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM_NUMBER = os.environ.get("TWILIO_FROM_NUMBER", "")


RAZORPAY_KEY_ID = os.environ.get("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.environ.get("RAZORPAY_KEY_SECRET")