# Generated by Django 6.0.3 on 2026-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
