# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0002_alter_advertisement_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(upload_to="hero/")),
                ("link_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "show_first",
                    models.BooleanField(
                        default=True,
                        help_text="When checked, this poster is the first slide (before the latest ads).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home page hero poster",
                "verbose_name_plural": "Home page hero posters",
                "ordering": ["-updated_at"],
            },
        ),
    ]
